spring.application.name=ai-analysis-report-service
server.port=8006

spring.cloud.nacos.server-addr=127.0.0.1:8848

# 数据库配置
spring.datasource.url=jdbc:mysql://localhost:3306/ai_analysis_service_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=12344321
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis配置
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=org.example.aianalysis.entity

# JobRunr配置
org.jobrunr.background-job-server.enabled=true
org.jobrunr.dashboard.enabled=true
org.jobrunr.dashboard.port=8086