spring.application.name=ai-analysis-report-service
server.port=8006

spring.cloud.nacos.server-addr=127.0.0.1:8848
spring.cloud.nacos.config.server-addr=127.0.0.1:8848
spring.config.import=nacos:ai-analysis-report-service
spring.cloud.nacos.config.file-extension=ai-analysis-report-service.json


# 数据库配置
spring.datasource.url=jdbc:mysql://localhost:3306/ai_analysis_service_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=12344321
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis配置
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=org.example.aianalysis.entity
mybatis.configuration.mapUnderscoreToCamelCase=true

# JobRunr配置
org.jobrunr.background-job-server.enabled=true
org.jobrunr.dashboard.enabled=true
org.jobrunr.dashboard.port=8086

# Feign配置
spring.cloud.openfeign.client-config.default.connect-timeout=5000
spring.cloud.openfeign.client-config.default.read-timeout=10000

# 默认城市编码
default.city.code=360113

# AI模型API配置
ai.model.api.url=https://spark-api-open.xf-yun.com/v1/chat/completions
ai.model.api.key=ihGvMWBRNZRdbKDTWORy:xjfQylQJkaATAqCUtYiO